version: '3.7'
services:
  website:
   build:
    context: .
   ports:
    - 80:80

  unit-test:
    volumes:
        - $PWD:/app
    build:
      dockerfile: rspec.dockerfile
      context: .
    entrypoint: rspec
    command:
      - /app/spec/unit/*_spec.rb
      - --pattern
    
    